### Variables

# Name
name: "otel-collector"

# Mode
mode: "daemonset"

# Prometheus
prometheus:
  port: 9464

# New Relic OTLP endpoint
newrelicOtlpEndpoint: "otlp.nr-data.net:4317"

# New Relic license key
newrelicLicenseKey: ""
