apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        instrumentation.opentelemetry.io/inject-java: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.dockerhubName }}/{{ .Values.imageName }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVER_ADDRESS
              value: {{ .Values.kafka.address }}
            - name: KAFKA_TOPIC
              value: {{ .Values.kafka.topic }}
            - name: PERSISTENCE_SERVICE_ENDPOINT
              value: {{ .Values.endpoints.persistence }}
          ports:
            - protocol: TCP
              containerPort: {{ .Values.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
